BarberiaNeris/Controllers/AgendamentoController.cs
using Business;
using Entities.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SendGrid;
using SendGrid.Helpers.Mail;
using System.Security.Claims;
using System.Text;

public class AgendamentoController : Controller
{
    private readonly AgendamentoBLL _agendamentoBLL;
    private readonly BarbeariaContext _context;
    private readonly IConfiguration _configuration;

    public AgendamentoController(AgendamentoBLL agendamentoBusiness, BarbeariaContext context, IConfiguration configuration)
    {
        _agendamentoBLL = agendamentoBusiness;
        _context = context;
        _configuration = configuration;
    }

    [HttpGet]
    public IActionResult Agendamento(string servico = "")
    {
        var barbeiros = _context.Barbeiros.ToList();
        ViewBag.Barbeiros = barbeiros;

        if (User.Identity.IsAuthenticated)
        {
            var clienteId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (!string.IsNullOrEmpty(clienteId))
            {
                var cliente = _context.Clientes.Find(int.Parse(clienteId));
                if (cliente != null)
                {
                    ViewBag.ClienteName = cliente.Nome;
                    ViewBag.ClienteEmail = cliente.Email;
                    ViewBag.ClientePhone = cliente.Telefone;
                }
            }
        }

        ViewBag.ServicoSelecionado = servico;

        return View();
    }

    [HttpGet]
    public IActionResult GetHorariosDisponiveis(int barbeiroId)
    {
        var horariosOcupados = GetHorariosOcupados(barbeiroId);

        var horariosDisponiveis = new List<DateTime>();
        var dataInicio = DateTime.Now.Date;

        for (int dia = 0; dia < 14; dia++) // Mostrar horários para os próximos 14 dias
        {
            var data = dataInicio.AddDays(dia);

            for (int hora = 9; hora < 18; hora++) // Horário das 9 às 18
            {
                var horario = data.AddHours(hora);
                if (!horariosOcupados.Contains(horario))
                {
                    horariosDisponiveis.Add(horario);
                }
            }
        }

        return Json(new
        {
            disponiveis = horariosDisponiveis,
            ocupados = horariosOcupados
        });
    }



    public List<DateTime> GetHorariosOcupados(int barbeiroId)
    {
        return _context.Agendamentos
                       .Where(a => a.BarbeiroID == barbeiroId)
                       .Select(a => a.DataHora)
                       .ToList();
    }


    [HttpPost]
    public IActionResult Agendamento(string name, string email, string phone, List<string> services, int barber, DateTime appointment)
    {       
        _agendamentoBLL.Agendar(name, email, phone, services, barber, appointment);

        // Defina uma variável ViewBag para indicar que o agendamento foi bem-sucedido
        ViewBag.AgendamentoSucesso = true;

        // Enviar e-mail de confirmação
        var teste = SendConfirmationEmail(email, name, barber, services, appointment);
        var barberEmail = _context.Barbeiros.FirstOrDefault(b => b.BarbeiroID == barber)?.Email;
        var barberName = _context.Barbeiros.FirstOrDefault(b => b.BarbeiroID == barber)?.Nome;
        if (!string.IsNullOrEmpty(barberEmail))
        {
            SendEmailToBarber(barberEmail, barberName, name, email, phone, services, appointment);
        }
        var barbeiros = _context.Barbeiros.ToList();
        ViewBag.Barbeiros = barbeiros;

        return View();
    }



    private async Task SendConfirmationEmail(string toEmail, string name, int barberId, List<string> services, DateTime appointment)
    {
        var apiKey = _configuration["EmailSettings:SendGridApiKey"];
        var client = new SendGridClient(apiKey);

        // Recuperar o nome do barbeiro com base no barberId
        var barber = _context.Barbeiros.FirstOrDefault(b => b.BarbeiroID == barberId);

        if (barber == null)
        {
            return;
        }

        var from = new EmailAddress("gduarte@sprintmind.com.br", "Barbearia Neris");
        var subject = "Agendamento Confirmado";
        var to = new EmailAddress(toEmail);

        // Usar o nome do barbeiro recuperado
        var barberName = barber.Nome;

        var corpoEmail = CorpoEmail(toEmail, name, barberName, services, appointment);

        var plainTextContent = $"Agendamento marcado com sucesso! Nome: {name} Cabeleireiro: {barberName} Serviço: {string.Join(", ", services)} Horário: {appointment}";

        var icsContent = GenerateICalendarEvent("Agendamento na Barbearia", appointment, appointment.AddHours(1));

        var attachment = new Attachment
        {
            Content = Convert.ToBase64String(Encoding.UTF8.GetBytes(icsContent)),
            Filename = "event.ics",
            Type = "text/calendar"
        };

        var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, corpoEmail);
        msg.AddAttachment(attachment);

        var response = await client.SendEmailAsync(msg);
    }

    private string GenerateICalendarEvent(string eventName, DateTime startTime, DateTime endTime)
    {
        var icsEvent = new StringBuilder();
        icsEvent.AppendLine("BEGIN:VCALENDAR");
        icsEvent.AppendLine("VERSION:2.0");
        icsEvent.AppendLine("PRODID:-//Barbearia Neris//Agendamento//PT");
        icsEvent.AppendLine("BEGIN:VEVENT");
        icsEvent.AppendLine($"DTSTART:{startTime:yyyyMMddTHHmmss}");
        icsEvent.AppendLine($"DTEND:{endTime:yyyyMMddTHHmmss}");
        icsEvent.AppendLine($"SUMMARY:{eventName}");
        icsEvent.AppendLine("END:VEVENT");
        icsEvent.AppendLine("END:VCALENDAR");
        return icsEvent.ToString();
    }

    private async Task SendConfirmationEmailBarbeiro(string toEmail, string name, int barberId, List<string> services, DateTime appointment)
    {
        var apiKey = _configuration["EmailSettings:SendGridApiKey"];
        var client = new SendGridClient(apiKey);

        // Recuperar o nome do barbeiro com base no barberId
        var barber = _context.Barbeiros.FirstOrDefault(b => b.BarbeiroID == barberId);

        if (barber == null)
        {

            return;
        }

        var from = new EmailAddress("gduarte@sprintmind.com.br", "Barbearia Neris");
        var subject = "Agendamento Confirmado";
        var to = new EmailAddress(toEmail);

        // Usar o nome do barbeiro recuperado
        var barberName = barber.Nome;


        var corpoEmail = CorpoEmail(toEmail, name, barberName, services, appointment);

        var plainTextContent = $"Agendamento marcado com sucesso! Nome: {name} Cabeleireiro: {barberName} Serviço: {services} Horário: {appointment}";
        var htmlContent = corpoEmail;

        var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
        var response = await client.SendEmailAsync(msg);
    }

    private async Task SendEmailToBarber(string barberEmail, string barberName, string clienteName, string clientEmail, string phone, List<string> services, DateTime appointment)
    {
        var apiKey = _configuration["EmailSettings:SendGridApiKey"];
        var client = new SendGridClient(apiKey);

        var from = new EmailAddress("gduarte@sprintmind.com.br", "Barbearia Neris");
        var subject = "Novo Agendamento";
        var to = new EmailAddress(barberEmail);

        var htmlContent = CorpoEmailBarbeiro(barberName, clienteName, clientEmail, phone, services, appointment);
        var plainTextContent = $"O cliente {clienteName} marcou um agendamento para {appointment.ToString("dd/MM/yyyy HH:mm")}. Serviços: {string.Join(", ", services)}";

        var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
        var response = await client.SendEmailAsync(msg);
    }

    public string CorpoEmailBarbeiro(string barberName, string clientName, string clientEmail, string clientPhone, List<string> services, DateTime appointment)
    {
        #region[CorpoHTML]
        string html = "<body style='width:100%; height: auto; background-color: #f6f6f6; margin: 0;'>";
        html += "<div style='width:100%; height:5px; background-color:#618D63;'></div>";
        html += "<table width='650' align='center' cellpadding='0' cellspacing='' style=' padding:10px 20px;'>";
        html += "<tr>";
        html += "<td style='text-align:center'>";
        html += "<img src='https://i.imgur.com/bTX9RuM.jpg' /> ";
        html += "</td>";
        html += "</tr>";
        html += "</table>";
        html += "<div style='display:block; border-radius: 8px; width: 650px; margin: 0 auto; box-shadow:0 4px 10px 0 rgba(0,0,0,0.2),0 4px 20px 0 rgba(0,0,0,0.19)'>";
        html += "<table cellpadding='0' cellspacing='0' style='width:100%;background-color:#fff;font-family: Helvetica,Arial,sans-serif; font-size: 14px; font-weight: 300; color: #818181; padding:10px 20px; border-radius: 0 0 8px 8px;'>";
        html += "<tr>";
        html += "<td class='content-wrap'>";
        html += "<table cellpadding='0' cellspacing='0' style='width: 100%;'>";
        html += "<td style='text-align:left'>";
        html += "<p><b>Olá</b> " + barberName + "," + "</p>";
        html += "<p>Um cliente marcou um agendamento através do nosso sistema.</p>";
        html += "<p>Aqui estão os detalhes:</p>";
        html += "<p>Nome do Cliente: " + clientName + "</p>";
        html += "<p>E-mail do Cliente: " + clientEmail + "</p>";
        html += "<p>Telefone do Cliente: " + clientPhone + "</p>";
        html += "<p>Serviços Agendados: " + string.Join(", ", services) + "</p>";
        html += "<p>Data e Hora Marcada: " + appointment + "</p>";
        html += "</td>";
        html += "</tr>";
        html += "<tr>";
        html += "<td style='text-align:center'>";
        html += "&nbsp;";
        html += "</td>";
        html += "<td style='text-align:center'>";
        html += "&nbsp;>";

BarberiaNeris/Controllers/LoginController.cs
using Business;
using Entities.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Collections.Generic;
using System.Security.Claims;

namespace BarberiaNeris.Controllers
{
    public class LoginController : Controller
    {
        private readonly BarbeariaContext _context;

        public LoginController(BarbeariaContext context)
        {
            _context = context;
        }

        [HttpPost]
        public async Task<IActionResult> Login(string email, string senha)
        {
            var cliente = _context.Clientes.FirstOrDefault(b => b.Email == email);

            if (cliente != null && BaseBLL.VerifyPassword(senha, cliente.Senha))
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, cliente.Nome),
                    new Claim(ClaimTypes.NameIdentifier, cliente.ClienteID.ToString()),
                    new Claim("Email", cliente.Email.ToString()),
                    new Claim("Telefone", cliente.Telefone.ToString()),
                };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                // Defina a propriedade IsPersistent para true
                var authProperties = new AuthenticationProperties
                {
                    IsPersistent = false
                };

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);

                // Redirecione para a página desejada após o login.
                return RedirectToAction("HistoricoAgendamentos", "Cliente");
            }
            else
            {
                // Informe o usuário que o email ou a senha estão incorretos.
                ModelState.AddModelError(string.Empty, "Email ou senha inválidos.");
                return View();  // Retorna para a página de login com a mensagem de erro.
            }
        }


        [HttpPost]
        public IActionResult CadastrarUsuario(string nome, string email, string telefone, string senha)
        {
            // Verificar se já existe um usuário com o mesmo e-mail
            var clienteExistente = _context.Clientes.FirstOrDefault(b => b.Email == email);

            
            if (clienteExistente == null)
            {
                var senhaCriptografada = BaseBLL.HashPassword(senha);

                var novoCliente = new Cliente
                {
                    Nome = nome,
                    Email = email,
                    Telefone = telefone,
                    Senha = senhaCriptografada,
                };

                _context.Clientes.Add(novoCliente);
                _context.SaveChanges();

                TempData["SuccessMessage"] = "Cadastro feito com sucesso!";
                ViewBag.CadastroConcluido = true;
                return RedirectToAction("Index", "Home"); // Redirecione para a página inicial após o cadastro
            }
            else if(clienteExistente != null && clienteExistente.Senha == null)
            {
                // Atualize os campos do cliente existente
                clienteExistente.Nome = nome;
                clienteExistente.Email = email;
                clienteExistente.Telefone = telefone;
                clienteExistente.Senha = BaseBLL.HashPassword(senha);
                // Persiste a atualização
                _context.SaveChanges();
                TempData["SuccessMessage"] = "Cadastro feito com sucesso!";
                ViewBag.CadastroConcluido = true;
                return RedirectToAction("Index", "Home"); // Redirecione para a página inicial após o cadastro
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Email já está em uso.");
                return View(); // Retorna para a página de registro com a mensagem de erro.
            }
        }

        [HttpPost]
        public IActionResult UpdateCadastro(int clienteId, string nome, string email, string telefone, string senha)
        {
            var clienteExistente = _context.Clientes.FirstOrDefault(c => c.Email == email);

            if (clienteExistente == null)
            {
                // Cliente não encontrado, trate o erro
                ModelState.AddModelError(string.Empty, "Cliente não encontrado.");
                return View(); // Retorna para a página de edição com a mensagem de erro.
            }

            // Atualize os campos do cliente existente
            clienteExistente.Nome = nome;
            clienteExistente.Email = email;
            clienteExistente.Telefone = telefone;
            clienteExistente.Senha = BaseBLL.HashPassword(senha);

            // Persiste a atualização
            _context.SaveChanges();

            TempData["SuccessMessage"] = "Cadastro atualizado com sucesso!";
            return RedirectToAction("Index", "Home");
        }


        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }
    }
}

BarberiaNeris/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Barbearia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Podkova:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js'></script>

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark custom-navbar border-bottom box-shadow fixed-top">
            <div class="container d-flex align-items-center">
                <!-- Logo da Barbearia -->
                <a class="navbar-brand" href="/#home">
                    <img src="~/imagens/logo_barbearia.jpeg" alt="Logo da Barbearia" width="100"> Barbearia Neris
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto d-flex gap-5">
                        @if (Context.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <span class="nav-link text-white">Olá, @Context.User.Identity.Name!</span>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Agendamento" asp-action="Agendamento">Agendamento</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Cliente" asp-action="HistoricoAgendamentos">Histórico</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" href="/#home">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" href="/#sobre">Sobre nós</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" href="/#servicos">Serviços</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" href="/#barbeiros">Nossos Barbeiros</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Agendamento" asp-action="Agendamento">Agendamento</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" id="accountDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Conta
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="accountDropdown">
                                    <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#loginModal">Entrar</a></li>
                                    <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#cadastroModal">Cadastrar</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Modal Entrar -->
    <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" style="color:black" id="loginModalLabel">Entrar</h5>
                    <button type="button" style="color:black" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
                </div>
                <div class="modal-body">
                    <form method="post" asp-controller="Login" asp-action="Login">
                        <div class="mb-3">
                            <label for="email" style="color: black" class="form-label">Email</label>
                            <input type="email" name="email" style="color: black" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Insira seu email" required>
                        </div>
                        <div class="mb-3">
                            <label for="senha" style="color:black" class="form-label">Senha</label>
                            <div class="input-group">
                                <input type="password" name="senha" style="color:black" class="form-control" id="senha" placeholder="Insira sua senha">
                                <button class="btn btn-outline-secondary" type="button" id="togglePassword">
                                    <i id="eyeIcon" class="fa fa-eye"></i>
                                </button>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Entrar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <div class="modal fade" id="cadastroModal" tabindex="-1" aria-labelledby="cadastroModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" style="color:black" id="cadastroModalLabel">Cadastrar</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="cadastroForm" method="post" action="/Login/CadastrarUsuario">
                        <div class="mb-3">
                            <label for="cadastroNome" style="color: black" class="form-label">Nome</label>
                            <input type="text" style="color: black" class="form-control" id="cadastroNome" name="Nome" placeholder="Insira seu nome" required>
                        </div>
                        <div class="mb-3">
                            <label for="cadastroEmail" style="color: black" class="form-label">Email</label>
                            <input type="email" style="color: black" class="form-control" id="cadastroEmail" name="Email" placeholder="Insira seu email" required>
                        </div>
                        <div class="mb-3">
                            <label for="cadastroTelefone" style="color: black" class="form-label">Telefone</label>
                            <input type="tel" style="color: black" class="form-control" id="cadastroTelefone" name="telefone" placeholder="insira seu telefone" required>
                        </div>
                        <label for="cadastroSenha" style="color: black" class="form-label">Senha</label>
                        <div class="mb-3 input-group">
                            <input type="password" style="color: black" class="form-control" id="cadastroSenha" name="Senha" placeholder="Insira uma senha" required>
                            <button class="btn btn-outline-secondary" type="button" id="toggleCadastroPassword"><i class="fa fa-eye"></i></button>
                        </div>
                        <button type="submit" class="btn btn-primary">Cadastrar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <input type="hidden" style="color:black" id="successMessage" value="@TempData["SuccessMessage"]" />
    <!-- Modal de Sucesso -->
    <div class="modal fade" id="successModal" tabindex="-1" aria-labelledby="successModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header bg-success text-white">
                    <h5 class="modal-title" id="successModalLabel">Cadastro bem-sucedido!</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body text-center">
                    <i class="fas fa-check-circle fa-4x text-success mb-3"></i>
                    <p style="color:black;">Cadastro feito com sucesso!</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success" data-bs-dismiss="modal">Ok</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal UpdateCadastro -->
    <input type="hidden" id="showUpdateModal" value="@TempData["ShowUpdateModal"]">
    <div class="modal fade" id="updateCadastroModal" tabindex="-1" aria-labelledby="updateCadastroModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" style="color:black" id="updateCadastroModalLabel">Atualizar Cadastro</h5>
                    <button type="button" style="color:black" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
                </div>
                <div class="modal-body">
                    <form method="post" asp-controller="Login" asp-action="UpdateCadastro">
                        <div class="mb-3">
                            <label for="updateNome" style="color: black" class="form-label">Nome</label>
                            <input type="text" style="color: black" class="form-control" id="updateNome" name="Nome" value="" placeholder="Insira seu nome" required>
                        </div>
                        <div class="mb-3">
                            <label for="updateEmail" style="color: black" class="form-label">Email</label>
                            <input type="email" style="color: black" class="form-control" id="updateEmail" name="Email" value="" placeholder="Insira seu email" required>
                        </div>
                        <div class="mb-3">
                            <label for="updateTelefone" style="color: black" class="form-label">Telefone</label>
                            <input type="tel" style="color: black" class="form-control" id="updateTelefone" name="telefone" value="" placeholder="insira seu telefone" required>
                        </div>
                        <div class="mb-3 input-group">
                            <input type="password" style="color: black" class="form-control" id="cadastroSenha" name="Senha" placeholder="Insira uma senha" required>
                            <button class="btn btn-outline-secondary" type="button" id="toggleCadastroPassword"><i class="fa fa-eye"></i></button>
                        </div>
                        <!-- Você pode adicionar mais campos conforme necessário -->
                        <button type="submit" class="btn btn-primary">Atualizar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>




    <footer class="border-top footer">
        <div class="container-fluid">
            &copy; 2023 - Barbearia
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>